# Railway Configuration File
# Este archivo le dice a Railway cómo construir la aplicación

[build]
builder = "NIXPACKS"

[build.env]
MAVEN_OPTS = "-Dmaven.test.skip=true"

[deploy]
startCommand = "java -Dserver.port=$PORT -jar target/chaski-backend-0.0.1-SNAPSHOT.jar"
healthcheckPath = "/"
healthcheckTimeout = 300

